- _layouts/default_en.html
- _layouts/default_ja.html
> Fix 個別メニューからトップが消えていたのを修正

- _candidates_en/JohnADeGoes_1.md
- _candidates_en/KailuoWang_1.md
- _candidates_en/ValentinKasas_1.md
- _layouts/candidates_en.html
- en/candidates/element.html
- ja/candidates/element.html
Zapier設定前に英語で申し込み来てた方の分を手動でGoogleFormから拾って追加。
ついでにアイコンをリスティングで表示するようにしてみました。
> add candidates in Enlgish / show icon in listing

- _candidates_en/Shinpei_1.md
> Shinpei-san's abstract that was provided by him

- README.md
- _candidates_en/GabrielePetronella_1.md
> Add "Move fast and fix things"

- _candidates_en/GabrielePetronella_2.md
Ref https://github.com/scalajp/2018.scalamatsuri.org/issues/24
> Add "Monad Transformers for the working programmer"

- _candidates_en/Nivedita_1.md
> Add "Baby steps to learning Scala"

- _includes/widgetoon.js.html
- _layouts/candidates_en.html
- _layouts/candidates_ja.html
- _layouts/default_en.html
- _layouts/default_ja.html
> Add twitter button with count

- _candidates_en/Nivedita_1.md
- _candidates_ja/Nivedita_1.md
> 和訳:Nivedita_1.md

- _candidates_en/RaulRaja_1.md
> Add "Building Microservices with Freestyle"

- _candidates_en/Nivedita_1.md
- _candidates_ja/Nivedita_1.md
LinkedInのサムネイルのURLを取得して書き換えました。
#37
> IconのURLがLinkedInのURLだったので画像のURLに変更

- _includes/footer.html
> Updated copyright notice

- _candidates_ja/KailuoWang_1.md
> Add Kailuo_Wang_1.md under _candidates_ja 

- _candidates_ja/ValentinKasas_1.md
> Add _candidates_ja/ValentinKasas_1.md 

- _candidates_en/TorigoeTakatomo_1.md
> Add _candidates_en/TorigoeTakatomo_1.md

- _candidates_en/Nivedita_1.md
- _candidates_ja/Nivedita_1.md
> Modify to SNS link

- _candidates_en/TorigoeTakatomo_1.md
- _candidates_ja/TorigoeTakatomo_1.md
> Modify to Github link

- _candidates_en/MartinThompson_1.md
> Add Functional Performance

- _candidates_ja/YoshitakaOkuda_1.md
> Add YoshitakaOkuda_1.md Ja

- _candidates_ja/YoshitakaOkuda_3.md
> Add YoshitakaOkuda_3 ja

- _candidates_ja/YoshitakaOkuda_2.md
> Add YoshitakaOkuda_2 Ja

- _candidates_en/YoshiteruTakeshita_1.md
> Add  _candidates_en/YoshiteruTakeshita_1.md

- _candidates_ja/YoshiteruTakeshita_1.md
> Add _candidates_ja/YoshiteruTakeshita_1.md

- _data/nav_zh-CN.yml
- _data/nav_zh-TW.yml
- index.html
- index_en.html
- index_zh-ch.html
- index_zh-cn.html
- index_zh-tw.html
せっかくアジア最大級を謳っているので、中国語版も用意しようかという試み
まずはトップページのみ
リソース少ないので応募内容とか講演内容とかまでは無理と思いますが、トップページやCFPくらいはあってもいいかも？というので先走って作りました
基本的には英語版ベースで作る感じで、中国語版のメンテナンスの責任は僕が持とうと思います
来年以降どうするの、とか気になるかもしれませんが、今年だけの試みになってもそれはそれでよいのではないでしょうか
簡体中文
繁体中文
> Chinese Edition

- _candidates_ja/YoshiteruTakeshita_1.md
> fix _candidate_ja/YoshiteruTakeshita_1.md

- _candidates_en/MichalMatloka_1.md
> Add _candidates_en/MichalMatloka_1.md

- _candidates_ja/_SotaroKimura_1.md
> Add SotaroKimura_1 Ja

- _candidates_ja/SotaroKimura_2.md
> Add SotaroKimura_2 Ja

- _candidates_ja/YoshiakiShibutani_1.md
> Add YoshiakiShibutani_1 Ja

- _candidates_ja/YoshitakaOkuda_1.md
- _candidates_ja/YoshitakaOkuda_2.md
- _candidates_ja/YoshitakaOkuda_3.md
すみません、 `https://...` を含めてしまっていました。
> Fix Twitter&Github links

- index_zh-cn.html
- index_zh-tw.html
スポンサーロゴを表示します
- 表示スペースだけ設置すればOK？
簡体中文
繁体中文
> Chinese Edition: Logos of sponsors

- _candidates_en/YoshitakaOkuda_2.md
> add _candidates_en/YoshitakaOkuda_2.md

- _layouts/default_en.html
- _layouts/default_ja.html
> Add link to chinese edition in the navbar of jp/en

- _candidates_en/JorgeSanchez_1.md
> Add JorgeSanchez_1 En

- _candidates_en/RenPillay_1.md
> Add RenPillay_1 En

- _candidates_en/YoshitakaOkuda_3.md
> add _candidates_en/YoshitakaOkuda_3.md

- _candidates_ja/DaisukeKasuya_1.md
> Fix DaisukeKasuya_1 Lang and Audience

- _candidates_ja/YoshiakiShibutani_1.md
> Fix 表示されていなかった箇所を修正

- _candidates_ja/YoshitakaFujii_1.md
> add _candidates_ja/YoshitakaFujii_1.md

- _candidates_ja/KaiSasaki_1.md
> add ja_KaiSasaki

- _candidates_en/KaiSasaki_1.md
> add en_KaiSasaki

- _candidates_ja/KaiSasaki_1.md
#129
すいません、アイコンとアカウント情報がまちがっていました。
> fix profile

- _candidates_en/DaisukeKasuya_1.md
Fixes https://github.com/scalajp/2018.scalamatsuri.org/issues/96
> Translate DaisukeKasuya_1

- _candidates_ja/JorgeSanchez_1.md
> Translate JorgeSanchez_1

- _candidates_ja/RenPillay_1.md
> Translate RenPillay_1

- _candidates_en/SotaroKimura_2.md
> Add _candidates_en/SotaroKimura_2.md

- _candidates_en/YoshitakaOkuda_1.md
> add en/YoshitakaOkuda_1.md

- _candidates_en/YoshitakaFujii_1.md
> add YoshitakaFujii_1.md

- _candidates_en/YoshiakiShibutani_1.md
> Translate Yotchang

- _config.yml
> Fix sponsor plans

- index_zh-cn.html
> Reword cfp and fix typo

- _candidates_en/RichardImaoka_1.md
> Add _candidates_en/RichardImaoka_1.md

- _candidates_en/RichardImaoka_2.md
> Add _candidates_en/RichardImaoka_2.md

- _candidates_ja/RichardImaoka_2.md
> Add _candidates_ja/RichardImaoka_2.md

- _candidates_ja/RichardImaoka_1.md
> Add _candidates_ja/RichardImaoka_1.md

- _candidates_en/JakubKozłowski_1.md
> Add candidates_en/JakubKozłowski_1.md

- _candidates_ja/YoheiTSUJI_1.md
> Add _candidates_ja/YoheiTSUJI_1.md

- _candidates_ja/YoheiTSUJI_1.md
ref https://github.com/scalajp/2018.scalamatsuri.org/issues/218#issuecomment-343037629
> Modify _candidates_ja/YoheiTSUJI_1.md

- _data/logos/shogun.yml
> fix maverick logo img url

- _candidates_en/DanielBeskin_1.md
> add en DanielBeskin_1

- _candidates_en/KevinEid_1.md
> Add _candidates_en/KevinEid_1.md

- _candidates_en/PathikritBhowmick_1.md
> Add _candidates_en/PathikritBhowmick_1.md

- _candidates_en/DavidVanGeest_1.md
> Add candidates_en/DavidVanGeest_1.md

- _candidates_en/ZiyangLiu_1.md
> Add _candidates_en/ZiyangLiu_1.md

- _candidates_ja/ManabuNakamura_1.md
> Add _candidates_ja/ManabuNakamura_1.md

- _candidates_ja/NorbertPreining_1.md
Closes #275
```
---
name: Norbert Preining
title: "First steps with ScalaFX"
length: 40
audience: Beginner
language: English
twitter: norbusan
github: norbusan
icon: http://www.preining.info/norbert-tux-small.jpg
organization: Accelia Inc.
tags:
- Tools, Intro to Scala
suggestions:
- GUI developer
---
Scala as front end development language? Yes!
Scala can use both the Swing toolkit as well as ScalaFX, 
a toolkit wrapping JavaFX into Scala. 
We introduce basics of development GUIs with ScalaFX, 
go through important UX controls, and discuss methods and pitfalls 
in keeping your application responsive.
Since GUI programming is inherently asyncronously, 
we will touch on events, observables as provided by ScalaFX, 
and concurrent programming, in particular Futures and Promises.
While some …
```
> Add _candidates_ja/NorbertPreining_1.md

- _candidates_en/KazuhiroSera_1.md
- _candidates_ja/KazuhiroSera_1.md
> Kazuhiro sera 1

- _candidates_en/MasatoAsahara_1.md
Closes #305
The translation was provided by the submitter.
@smroy are you able to check the translation?
> Add _candidates_en/MasatoAsahara_1.md 

- _candidates_en/BasGeerdink_1.md
> add BasGeerdink_1.md

- _notice/cyberagent.md
サイバーエージェントさまからのご要望で、ボタンの文言を変更します。
変更前）応募する
変更後）詳しくはこちら
> サイバーエージェントさま掲載情報修正

- _candidates_ja/Yoshida_1.md
> Add _candidates_ja/Yoshida_1.md

- _data/logos/bugyo.yml
はてなさまより、奉行スポンサーのロゴを侍スポンサーと同じものに統一して欲しいとご要望がありました。
ロゴ修正のPRです。
> はてなさま奉行ロゴ修正

- _candidates_en/Yoshida_1.md
> Add _candidates_en/Yoshida_1.md

- _candidates_en/IlyaKirillov_1.md
> Add _candidates_en/IlyaKirillov_1.md

- _candidates_ja/DavidVanGeest_1.md
> translate DavidVanGeest_1

- _candidates_ja/KonradMalawski_1.md
Closes #345 
---
name: Konrad `ktoso` Malawski
title: "Distribute All The Things (with Akka)"
length: 40
audience: Intermediate
language: English
twitter: ktosopl
github: ktoso
icon: https://scontent-nrt1-1.xx.fbcdn.net/v/t31.0-8/15626425_10202875601369012_2764589549729738273_o.jpg?oh=57591212f91d0b834b45ff9806e05ec8&oe=5A921F16
organization: Akka Team, Lightbend
tags:
- Software Design and Architecture, Microservices, Others
suggestions:
- Developers interested in building performant and reliable systems. No prior exposure to Akka is needed to enjoy the session.
---
With Akka's recent focus, and accomplishment of shipping Akka Streams and having included Reactive Streams (java.util.concurrent.Flow) in the OpenJDK (Java 9), one has to wonder -- what's the next focus point for the Akka …
> add konrad-malawski-ja-1

- _candidates_en/EugeneYokota_1.md
> translate EugeneYokota_1

- _candidates_en/EugeneYokota_2.md
> translate EugeneYokota_2

- _candidates_ja/MitsuhiroShibuya_1.md
> Add _candidates_ja/MitsuhiroShibuya_1.md

- _candidates_en/JacekKunicki_1.md
> Add _candidates_en/JacekKunicki_1.md

- _candidates_en/NevilleLi_1.md
> Add _candidates_en/NevilleLi_1.md

- _candidates_en/Takayuky_1.md
> translate Takayuky_1

- _candidates_en/NaokiAoyama_1.md
> translates NaokiAoyama_1

- _candidates_ja/Jooohn1234_1.md
> Add _candidates_ja/Jooohn1234_1.md

- _candidates_en/JaspervanZandbeek_1.md
> Add _candidates_en/JaspervanZandbeek_1.md

- _candidates_en/Osiire_1.md
> translate Osiire_1

- _candidates_ja/PathikritBhowmick_1.md
Closes #284
```
---
name: Pathikrit Bhowmick
title: "Introduction to Cats using Algebraic Graphs"
length: 40
audience: Beginner
language: English
twitter: pathikrit_wrick
github: pathikrit
icon: https://avatars0.githubusercontent.com/u/899219?s=460&v=4
organization: Coatue Management
tags:
- Functional Programming
suggestions:
- People used to Scala but has never used Cats or done anything with category theory concepts.
---
We will introduce a minimalist purely functional abstraction to represent Graphs in Scala using
concepts from Category Theory using the cats Scala library.
```
> Add _candidates_ja/PathikritBhowmick_1.md

- _candidates_en/LarsHupel_1.md
> Add _candidates_en/LarsHupel_1.md

- _candidates_ja/IlyaKirillov_1.md
> translate IlyaKirillov_1

- _candidates_en/Jooohn1234_1.md
> translate Jooohn1234_1

- _candidates_ja/JacekKunicki_1.md
> translate JacekKunicki_1.md

- _candidates_en/Jooohn1234_1.md
> Making a minor change to send in a new pull request

- _candidates_ja/YuichiIkeda_1.md
> Add "Scalaで作る決済システム"

- _candidates_en/AlejandroLujan_1.md
> Add _candidates_en/AlejandroLujan_1.md

- _candidates_en/QuentinADAM_1.md
> Add _candidates_en/QuentinADAM_1.md

- _candidates_ja/ShinichiMorimoto_1.md
> Add _candidates_ja/ShinichiMorimoto_1.md

- _candidates_en/MarkusHauck_1.md
> Add _candidates_en/MarkusHauck_1.md

- _candidates_ja/KazukiNegoro_1.md
> Add _candidates_ja/KazukiNegoro_1.md

- _candidates_en/MarcinMatuszak_1.md
> Add _candidates_en/MarcinMatuszak_1.md

- _candidates_en/DaleWijnand_1.md
> Add _candidates_en/DaleWijnand_1.md

- _candidates_en/DaleWijnand_2.md
> Add _candidates_en/DaleWijnand_2.md

- _candidates_en/DaleWijnand_3.md
> Add _candidates_en/DaleWijnand_3.md

- _candidates_en/MarcinMatusak_1.md
> Add _candidates_en/MarcinMatusak_1.md

- _candidates_en/DanielaSfregola_1.md
Reduced abstract to less than 600 chars as request
> #286 Abstract under 600 chars

- _candidates_ja/LarsHupel_1.md
> translate LarsHupel_1

- _candidates_en/TaisukeOe_1.md
> add TaisukeOe en

- _candidates_en/KazukiNegoro_1.md
> translate KazukiNegoro_1

- _candidates_en/FranciscoPerez_1.md
> Add _candidates_en/FranciscoPerez_1.md

- _candidates_en/ShinichiMorimoto_1.md
> translate ShinichiMorimoto_1

- _candidates_en/YuichiIkeda_1.md
Please review @smroy @eed3si9n  @okapies 
Thanks!
> add YuichiIkeda-san's en / fix #458

- _candidates_en/NoamAlmog_1.md
> Add _candidates_en/NoamAlmog_1.md

- _candidates_en/KotaMizushima_1.md
fix #510 
Pls review @smroy @eed3si9n @okapies @richardimaoka
> add KotaMizushima-en

- _candidates_ja/MarcinMatuszak_2.md
> translate MarcinMatuszak_2.md

- _candidates_ja/QuentinADAM_1.md
> translate QuentinADAM_1.md to Japanese

- _candidates_ja/JustinKaeser_1.md
> translate JustinKaeser_1

- _candidates_ja/DaleWijnand_1.md
> translate DaleWijnand_1

- _candidates_ja/DaleWijnand_2.md
> translate DaleWijnand_2

- _candidates_ja/MasayaDake_1.md
アイコンのURLが微妙かもしれないです。mergeの時に確認お願いします。
> add ja MasayaDake_1.md

- _candidates_ja/DaleWijnand_3.md
> translate DaleWijnand_3.md to Japanese

- _candidates_en/JanChristopherVogt_1.md
> add JanChristopherVogt_1.md

- _candidates_en/JanChristopherVogt_2.md
> add JanChristopherVogt_2.md

- _candidates_en/HimanshuGupta_1.md
> Add _candidates_en/HimanshuGupta_1.md

- _candidates_ja/Awekuit_2.md
> Modify 2人で発表されるとの連絡があったため対応

- _candidates_en/RatanSebastian_2.md
> Add _candidates_en/RatanSebastian_2.md

- _candidates_en/RatanSebastian_1.md
> Add _candidates_en/RatanSebastian_1.md

- _candidates_ja/Ryota_1.md
> Add _candidates_ja/Ryota_1.md

- _candidates_en/LoicKnuchel_2.md
> Add _candidates_en/LoicKnuchel_2.md

- _candidates_en/LoicKnuchel_1.md
> Add _candidates_en/LoicKnuchel_1.md

- _candidates_en/AndreaPeruffo_1.md
> add AndreaPeruffo_1

- _candidates_en/Kim-EeYeoh_1.md
> add Kim-EeYeoh_1.md

- _candidates_en/Kim-EeYeoh_2.md
> add Kim-EeYeoh_2.md

- _candidates_ja/TomoyukiShimomura_1.md
> Add _candidates_ja/TomoyukiShimomura_1.md

- _candidates_en/PrabhatKashyap_1.md
> Add _candidates_en/PrabhatKashyap_1.md

- _candidates_en/AnilWadghule_1.md
Sending PR as per https://github.com/scalajp/2018.scalamatsuri.org/pull/542#issuecomment-352094976 comment
> Reduce abstrat to < 600 characters

- _candidates_en/phenan_1.md
> Add phenan en 1

- _candidates_en/TatsuyaAtsumi_1.md
> _candidates_en/TatsuyaAtsumi_1.md

- _candidates_en/YugoMaede_1.md
> Add _candidates_en/YugoMaede_1.md

- _candidates_en/ToyoshimaMasaki_1.md
> translate ToyoshimaMasaki_1

- _candidates_en/MasayaDake_1.md
> translate MasayaDake_1

- _candidates_en/JunichiKato_1.md
> Add _candidates_en/JunichiKato_1.md

- _candidates_en/YusukeYasuda_1.md
> translate YusukeYasuda_1

- _candidates_en/ToshiyukiTakahashi_1.md
Closes #576
Hi @smroy could you please review this?
Thanks
> Add _candidates_en/ToshiyukiTakahashi_1.md

- _data/nav_en.yml
- _data/nav_ja.yml
- _data/nav_zh-CN.yml
- _data/nav_zh-TW.yml
- index_zh-cn.html
- index_zh-tw.html
> CFPCloseの追加修正

- _candidates_en/BhavyaAggarwal_1.md
> Add _candidates_en/BhavyaAggarwal_1.md

- _candidates_en/SahilSawhney_1.md
> Add _candidates_en/SahilSawhney_1.md

- _candidates_en/LeifWickland_1.md
> Add _candidates_en/LeifWickland_1.md

- _candidates_en/AndyScott_1.md
> Add _candidates_en/AndyScott_1.md

- _candidates_en/SilviaPatriciaMouraPina_1.md
> Add _candidates_en/SilviaPatriciaMouraPina_1.md

- _candidates_ja/TakeshiItoh_1.md
> Add _candidates_ja/TakeshiItoh_1.md

- _candidates_en/AndyScott_2.md
> Add _candidates_en/AndyScott_2.md

- _candidates_ja/KotaroTanahashi_YoshihitoHotta_1.md
> Add _candidates_ja/KotaroTanahashi_YoshihitoHotta_1.md

- _candidates_en/DaddyLuteteSwami_1.md
> Add _candidates_en/DaddyLuteteSwami_1.md

- _candidates_en/NarcisseMbunzamaLokwa_1.md
> Add _candidates_en/NarcisseMbunzamaLokwa_1.md

- _candidates_ja/Halcat_1.md
> Add _candidates_ja/Halcat_1.md

- _candidates_en/AndreasHadimulyono_1.md
> Add _candidates_en/AndreasHadimulyono_1.md

- _candidates_ja/TakahiroTakashima_1.md
> Add _candidates_ja/TakahiroTakashima_1.md

- _candidates_en/OmervanKloeten_1.md
> Add _candidates_en/OmervanKloeten_1.md

- _candidates_ja/HiroshiIto_1.md
> Add _candidates_ja/HiroshiIto_1.md

- _candidates_ja/YoshiakiShibutani_2.md
> Add _candidates_ja/YoshiakiShibutani_2.md

- _candidates_ja/HiroshiIto_2.md
> Add _candidates_ja/HiroshiIto_2.md

- _candidates_en/PawełCesarSanjuanSzklarz_1.md
> Add _candidates_en/PawełCesarSanjuanSzklarz_1.md

- _candidates_en/Ma2k8_1.md
fix #580 
ref #574 
@smroy Could you check it? Thank you.
> translate ja/Ma2k8_1.md

- _candidates_en/JonathanWINANDY_1.md
> Add _candidates_en/JonathanWINANDY_1.md

- _candidates_en/Awekuit_1.md
> translate Awekuit_1

- _candidates_en/SidharthKhattri_1.md
> Add _candidates_en/SidharthKhattri_1.md

- _candidates_ja/TomokazuMatsushita_1.md
> Add _candidates_ja/TomokazuMatsushita_1.md

- _candidates_en/KrzysztofKrawiec_1.md
> Add _candidates_en/KrzysztofKrawiec_1.md

- _candidates_ja/Applideveloper_1.md
> Add _candidates_ja/Applideveloper_1.md

- _candidates_ja/CheshireCat_1.md
> Add _candidates_ja/CheshireCat_1.md

- _candidates_en/TomerGabel_1.md
> Add _candidates_en/TomerGabel_1.md

- _candidates_en/TomerGabel_2.md
> Add _candidates_en/TomerGabel_2.md

- en/candidates/index.html
- ja/candidates/index.html
https://github.com/scalajp/2018.scalamatsuri.org/pull/698 https://github.com/scalajp/2018.scalamatsuri.org/pull/707
> 応募セッション一覧ページから、募集ページヘのリンク削除

- _candidates_en/TomoyoshiOgura_1.md
fix #578
ref #573
@smroy Could you review this? Thanks!
> translate TomoyoshiOgura_1.md

- _candidates_ja/TalPressman_1.md
> translate TalPressman_1.md

- _candidates_en/CHETANKUMARKHATRI_1.md
> Add _candidates_en/CHETANKUMARKHATRI_1.md

- _candidates_en/TakeshiItoh_1.md
> Add _candidates_en/TakeshiItoh_1.md

- _candidates_ja/KasiaKittel_1.md
> translate KasiaKittel_1.md

- _candidates_en/TomerGabel_3.md
> Add _candidates_en/TomerGabel_3.md

- _candidates_ja/NoamAlmog_1.md
> translate NoamAlmog_1.md to Japanese

- _candidates_ja/AnilWadghule_1.md
> translate AnilWadghule_1

- _candidates_ja/MarkusHauck_1.md
> translate MarkusHauck_1

- _candidates_ja/BhavyaAggarwal_1md
> Add BhavyaAggarwal_1.md.

- _candidates_ja/TomerGabel_2.md
> translate TomerGabel_2

- _candidates_ja/JanChristopherVogt_1.md
Pls review @eed3si9n @grimrose @takezoux2
> fix #633 / translate CBT

- _candidates_ja/KrzysztofKrawiec_1.md
> Add _candidates_ja/KrzysztofKrawiec_1.md

- _candidates_ja/RatanSebastian_1.md
- target/.history
> Add _candidates_ja/RatanSebastian_1.md

- _candidates_ja/AndrewMartin_1.md
> translate AndrewMartin_1.md

- _candidates_ja/PrabhatKashyap_1.md
> translate PrabhatKashyap_1

- _candidates_ja/SidharthKhattri_1.md
fix #729
ref #699
タイトルは意図的にそのままにしました。
> translate SidharthKhattri_1.md

- _candidates_en/PetrZapletal_1.md
> shorter version I got from Petr

- _candidates_en/Halcat_1.md
fix #713
ref #690
@smroy please check it!
> translate Halcat_1.md

- _candidates_en/TomoyukiShimomura_1.md
fix #641
ref: #624
@smroy please check it!
> translate ja/TomoyukiShimomura_1.md

- _candidates_en/KotaroTanahashi_YoshihitoHotta_1.md
> translate ja/KotaroTanahashi_YoshihitoHotta_1.md

- _candidates_en/Awekuit_2.md
> translate Awekuit_2

- _candidates_en/Ryota_1.md
> translate Ryota_1.md

- _candidates_en/TakahiroTakashima_1.md
> translate TakahiroTakashima_1.md

- _candidates_en/HiroshiIto_1.md
> translate HiroshiIto_1

- _candidates_en/HiroshiIto_2.md
> translate HiroshiIto_2.md

- _candidates_en/YoshiakiShibutani_2.md
> translate YoshiakiShibutani_2

- _candidates_en/TomokazuMatsushita_1.md
> translate TomokazuMatsushita_1

- _candidates_en/Applideveloper_1.md
> translate Applideveloper_1

- _candidates_en/CheshireCat_1.md
> translate CheshireCat_1

- _candidates_ja/AndyScott_2.md
> translate AndyScott_2

- _candidates_en/KarthikBharadwajThirumalai_1.md
- _candidates_ja/KarthikBharadwajThirumalai_1.md
Per Eduardo's request via e-mail to me
> Add Eduardo as a co-speaker

- _candidates_en/JanChristopherVogt_2.md
#630 によると、Intermediate が正しいはず。
(和訳のほうは Intermediate になっていました)
> fix audience

- _layouts/default_en.html
- _layouts/default_ja.html
- js/cfp-voting.js
Firebase 側で新規プロジェクトを作成して、Google認証、Twitter連携、Github連携のセットアップをしました。
realtimedatabseのルールはコピー済み。
> 投票システムの組み込み

- _candidates_ja/BasGeerdink_2.md
> add Bas 2 ja

- _candidates_en/MichaelSlinn_1.md
- _candidates_ja/MichaelSlinn_1.md
> 仮想通貨のセッションにVirtualCoinのタグ追加

- _candidates_en/CHETANKUMARKHATRI_1.md
What were proposed in this Pull Request ?
* Spell mistake of one of the Spark Scala Transformation has been been corrected.
> Spell mistake has been changed

- _data/nav_en.yml
- _data/nav_ja.yml
- _data/nav_zh-CN.yml
- _data/nav_zh-TW.yml
- en/travel/index.html
- ja/travel/index.html
ref https://github.com/scalajp/2018.staff/issues/103
任意予約になったので、ホテル予約部分を大幅に削りました。
> トラベルページを追加

- ja/sponsors/index.html
> Add sponsors interview

- en/slides/index.md
特に変える程でもないのですが、この方が分かりやすいでしょうか？
> Very minor changes for clarity.

- _config.yml
- _includes/day0_overview.html
- css/common.css
> Add day0 ticket widget

- _data/program_en.yml
- _data/program_ja.yml
- _includes/program/day1.html
- _includes/program/day2.html
懇親会会場への移動時間を考慮したタイムテーブルへの変更しました。
それに伴い、幾つかのセッションをday2へ移動しました。
> Update time table

- _data/program_en.yml
- _data/program_ja.yml
- _includes/program/day1.html
- _includes/program/section.html
- _includes/program/utage.html
- css/common.css
> Add party section

- _candidates_en/KazuhiroSera_1.md
- _candidates_ja/KazuhiroSera_1.md
Just the other day, I've changed my Twitter icon image. As a result, the old one became unavailable. This pull request fixes the dead link caused by the matter.
> Fix the dead link (@seratch's icon image)

- index.html
- index_en.html
- index_zh-cn.html
- index_zh-tw.html
> Move section

- _data/nav_en.yml
- _data/nav_ja.yml
ref: #900 
スポンサー募集のページを終了
チケットのセクションを追加
> Modify ナビゲーションバーの整理

- css/common.css
- index.html
- index_en.html
- index_zh-cn.html
- index_zh-tw.html
当日スタッフの募集をclose
チケットの位置をスポンサーの下へ変更
> Fix top page

- _includes/program/section.html
This reverts commit 99d7c4c9ab6e6b24cea56c7a48c875c354951c37.
> Revert "Modify 一時的にアンカンファレンスのみ表示するように変更"

- _candidates_en/YoshiteruTakeshita_1.md
- _candidates_ja/YoshiteruTakeshita_1.md
> Add Takeshita's slide link

- _data/nav_en.yml
- _data/nav_ja.yml
- _data/staff.yml
- _includes/staff_entry_en.html
- _includes/staff_entry_ja.html
- en/staff/index.html
- ja/staff/index.html
> Add staff list

- _data/commercial.yml
- _data/nav_en.yml
- _data/nav_ja.yml
- _includes/commercial_en.html
- _includes/commercial_ja.html
- en/commercial/index.html
- ja/commercial/index.html
> Add commercials
